// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuBm0ZT40ZEQha3_7TcUcAOrZ-EUWyvw',
    appId: '1:862535069781:web:5656885982f8d565d164dc',
    messagingSenderId: '862535069781',
    projectId: 'we-chat-31137',
    authDomain: 'we-chat-31137.firebaseapp.com',
    storageBucket: 'we-chat-31137.firebasestorage.app',
    measurementId: 'G-GMZFS1QETS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vfWo0yGhbg1eq07vHEP-CSjj3q20Hx8',
    appId: '1:862535069781:android:c13c3e715c796f36d164dc',
    messagingSenderId: '862535069781',
    projectId: 'we-chat-31137',
    storageBucket: 'we-chat-31137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8kWZ1MYQOMqj8Hkv6o9xvOyI1eyUxx5E',
    appId: '1:862535069781:ios:641ec9a800ece1c4d164dc',
    messagingSenderId: '862535069781',
    projectId: 'we-chat-31137',
    storageBucket: 'we-chat-31137.firebasestorage.app',
    androidClientId: '862535069781-q9k1c7b8raf9284douk876pb208ktcei.apps.googleusercontent.com',
    iosClientId: '862535069781-g9ocuc9onk9m172dfierqfubs27tnfss.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8kWZ1MYQOMqj8Hkv6o9xvOyI1eyUxx5E',
    appId: '1:862535069781:ios:641ec9a800ece1c4d164dc',
    messagingSenderId: '862535069781',
    projectId: 'we-chat-31137',
    storageBucket: 'we-chat-31137.firebasestorage.app',
    androidClientId: '862535069781-q9k1c7b8raf9284douk876pb208ktcei.apps.googleusercontent.com',
    iosClientId: '862535069781-g9ocuc9onk9m172dfierqfubs27tnfss.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYuBm0ZT40ZEQha3_7TcUcAOrZ-EUWyvw',
    appId: '1:862535069781:web:a2741f77d83171f1d164dc',
    messagingSenderId: '862535069781',
    projectId: 'we-chat-31137',
    authDomain: 'we-chat-31137.firebaseapp.com',
    storageBucket: 'we-chat-31137.firebasestorage.app',
    measurementId: 'G-GYB0WW722S',
  );

}